// All site copy and data in one place. Edit here, then run `npm run build` to regenerate public/*.html.
// Everything below is published as-is, so keep it accurate: no placeholder numbers or invented claims.

module.exports = {
  calendly: 'https://calendly.com/krupal-demazetech/30min',
  email: 'contact@demazetech.com',
  address: 'A 804, Ganesh Glory 11, Jagatpur road, Near S.G. Highway, Gota, Ahmedabad',
  mapUrl: 'https://www.google.com/maps/dir//D-814,+Ganesh+Glory+11,+Jagatpur+Road,+Sarkhej+-+Gandhinagar+Hwy,+Gota,+Ahmedabad,+Gujarat+382470/@23.1141548,72.4578552,12z',
  socials: [
    { name: 'LinkedIn', href: 'https://www.linkedin.com/in/krupalchaudhary', icon: 'linkedin' },
    { name: 'X', href: 'https://x.com/growwithkrupal', icon: 'x' },
    { name: 'Instagram', href: 'https://www.instagram.com/demaze_technologies', icon: 'instagram' },
  ],
  logoMark: './assets/img/logo.png',
  tagline: 'We combine AI, software engineering, and automation with deep industry expertise to build scalable, sustainable solutions, working alongside you as a trusted, long-term partner.',

  hero: {
    eyebrow: ['Expertise', 'Innovation', 'Partnership'],
    headline: 'Your Strategic Partner in Building Scalable AI Products',
  },

  founder: {
    quote: 'We harness your vision and data to build AI-driven solutions that help your brand stand out and grow revenue. When you thrive, we thrive - and we’re with you, executing every step of the way.',
    name: 'Krupal Chaudhary',
    title: 'Founder & CEO',
    photo: 'krupal-chaudhary',
    href: 'https://www.linkedin.com/in/krupalchaudhary',
  },

  metrics: [
    { value: 45, prefix: '', suffix: '+', label: 'Projects Delivered' },
    { value: 10, prefix: '$', suffix: 'M+', label: 'Client Value Generated' },
    { value: 35, prefix: '', suffix: '+', label: 'Expert Team Members' },
    { value: 6, prefix: '', suffix: '+', label: 'Years of Excellence' },
  ],

  // Order matches the live /projects page; the first four are the homepage selection.
  projects: [
    { title: 'AI-Based software for luxury car dealers', image: 'ai-based-software-for-luxury-car-dealers', tint: '#dfe6ff',
      description: "This comprehensive AI-based software solution was developed for one of India's largest luxury car dealerships to streamline various operations, including used car valuation, new car EMI calculations, car refurbishment management, and serving as a powerful backend system for the sales team. The tool enhances operational efficiency and significantly improves the customer experience, making it an indispensable asset for the dealership.",
      features: ['Accurate Used Car Valuations', 'Instant New Car EMIs', 'Seamless Car Refurbishment', 'Efficient Sales Team Backend'] },
    { title: 'Investigative Case Management Software', image: 'investigative-case-management-software', tint: '#e9e2ff',
      description: 'It is an advanced web-based software designed to enhance the capabilities of private investigators with AI-powered tools and comprehensive case management features. It supports seamless organization of case information and media, secure data storage, and automated workflow management, accessible from anywhere.',
      features: ['Case Management', 'AI-Powered Tools', 'Document Automation, Subscription-based Auto deposit pricing model', 'Web-Based Access & Data Security'] },
    { title: 'AI-Powered luxury eCommerce Platform', image: 'ai-powered-luxury-ecommerce-platform', tint: '#dcf3e6',
      description: 'Developed a modern e-commerce and lifestyle platform focused on sustainability and luxury retail. The project involved designing and implementing intuitive user journeys, personalization mechanisms, and secure data handling to ensure a premium digital experience. The result was a scalable, user-friendly solution aligned with the client’s vision for innovation and environmental responsibility.',
      features: ['AI-Powered Search, Try-ons, Recommendations, Price models', 'AI-Powered Dashboard & Analytics, Custom Drag & Drop CMS', 'Live Selling, Workflow Automations, Product Authentication', 'Smart Order & Inventory Management'] },
    { title: 'Senior Engagement & Support platform', image: 'senior-engagement-and-support-platform', tint: '#fff1cf',
      description: 'Sukoon Unlimited is an innovative platform designed to help seniors lead a connected, purposeful, and fulfilled life by providing access to support, meaningful conversations, and activities. The platform offers various services including personalized coaching, meetups, and a community of compassionate individuals, all aimed at reducing isolation and fostering connections. Sukoon Unlimited serves as a dedicated space for seniors to share experiences, seek guidance, and participate in enriching discussions that enhance mental and emotional well-being.',
      features: ['Speak with Sarathis, Club Sukoon', 'Coaching and Counseling', 'Meetups and Social Engagements', 'Sukoon Corner Blog'] },
    { title: 'Multi-vendor eCommerce Marketplace', image: 'multi-vendor-ecommerce-marketplace', tint: '#ffe0e6',
      description: 'It is Australian and New Zealand’s leading online marketplace where shoppers, good causes and retailers can do better shopping to get the latest trends, shoes, dresses, accessories and more. This app contains many features like category-wise products, easy searching, wishlist, brands, drop auction, currency converter, add to cart and buy with many payment options.',
      features: ['Enhanced Shopping Experience', 'Increased Reach for Retailers', 'Multi-vendor features, Live Auction', 'Achieved 99% Lighthouse Score'] },
    { title: 'Multi-shoppers Food & Grocery Delivery App', image: 'multi-shoppers-food-and-grocery-delivery-app', tint: '#e2f6d5',
      description: 'It is a cross-platform application developed using Flutter for user-facing apps and ReactJS for the admin panel. The platform is designed to empower local shop vendors by enabling them to sell their products online and manage their digital stores efficiently. It provides a seamless experience for both customers and shop owners, offering features that facilitate easy product listing, inventory management, and customer interaction.',
      features: ['Buy Grocery, Household Items, & Restaurant’s food', 'User App, Seller App, Rider (Delivery Person) App', 'Customer & Delivery Management, Account Management', 'Complete Control of Digital Store, Delivery Areas Setting'] },
    { title: 'Car service & customer engagement platform', image: 'car-service-and-customer-engagement-platform', tint: '#dfe6ff',
      description: 'The platform is a web and mobile-based application designed to enhance the efficiency of the service department of an authorized car dealership in India. The platform streamlines customer data management, service tracking, automated communication, and role-based access to improve operational efficiency and enhance customer experience. The application automates service reminders, tracks customer interactions, and provides real-time analytics to optimize the dealership’s Preventive Maintenance (PM), General Repairs (GR), and Body & Paint (BP) services.',
      features: ['Data Management & Integration', 'Admin Dashboard & Reporting', 'Automated Communication & Customer Engagement', 'Role-Based User Access, Customer Data Management'] },
    { title: 'B2B Gift Marketplace', image: 'b2b-gift-marketplace', tint: '#ffe8d6',
      description: 'It is a comprehensive multi-vendor e-commerce platform developed to streamline the gifting business by connecting resellers and manufacturers in a seamless ecosystem. Designed with scalability, automation, and efficiency in mind, it enables resellers to grow their business, manufacturers to scale production, and administrators to oversee the entire system effortlessly.',
      features: ['Reseller Application', 'Manufacturer Portal', 'AI-Powered Product Discovery', 'Admin Dashboard & Analytics'] },
    { title: 'Global Payment transfer platform', image: 'global-payment-transfer-platform', tint: '#e9e2ff',
      description: 'It is an advanced digital payment platform that utilizes blockchain technology to simplify global money transfers. With a focus on efficiency and security, it enables fast, low-cost, and seamless cross-border transactions using stablecoins. By removing traditional banking intermediaries, it reduces transaction costs and processing times. Whether for personal or business transactions, It ensures funds are transferred quickly, safely, and affordably, offering a more accessible financial solution for individuals and businesses worldwide.',
      features: ['Global Payments', 'Blockchain Technology', 'Stablecoin Integration', 'User Empowerment'] },
    { title: 'CMA Report Generation Software', image: 'cma-report-generation-software', tint: '#dcf3e6',
      description: 'The Credit Monitoring Arrangement (CMA) Report Generation Software is a cloud-based platform designed to streamline and automate the preparation of CMA reports. Developed using ReactJS and NodeJS, this platform includes comprehensive features that enable users to create detailed reports with all necessary data tables and charts. The software allows users to prepare, edit, and finalize CMA reports efficiently and provides options to download the reports in PDF and Excel formats.',
      features: ['Comprehensive Data Tables and Charts', 'Cloud-Based Platform', 'PDF and Excel Downloads', 'Efficient Report Preparation'] },
    { title: 'Recruitment platform', image: 'recruitment-platform', tint: '#fff1cf',
      description: 'This is a recruitment consultancy platform that streamlines the hiring process for businesses of all types. With its user-friendly interface and powerful features, It makes it easy for employers to find, manage, and track the progress of job candidates. The platform allows employers to create job listings. It also provides a real-time chat feature for communication between employers & employees. The platform also allows businesses to track the progress of candidates throughout the hiring process, from application to offer letter. With it, businesses can save time and resources while finding the best candidates for their open positions and candidates can find their best employers to join in the new organisation.',
      features: ['Job Listing Creation', 'Real-Time Chat Functionality', 'Candidate Progress Tracking', 'Analytics & Reporting Tools'] },
    { title: 'Task, Staff & Document management platform', image: 'task-staff-and-document-management-platform', tint: '#ffe0e6',
      description: 'It is a cross-platform application designed to digitally transform insurance and investment agencies by streamlining tasks, staff, and document management. Built for admins, heads, and field & office staff, the platform enables seamless task assignment, real-time communication, and document handling. With real-time messaging (powered by WebSockets), team members can collaborate efficiently, while heads can track progress and follow up on tasks. The system ensures secure document storage, categorizing files under respective policy or investment holders, making retrieval quick and organized.',
      features: ['Cross-Platform Task Management', 'Task Status Updates & Follow-Ups', 'Family Wise Document Upload & Search', 'Enhanced Workflow Efficiency'] },
    // TODO(content): this project still needs its own description; an empty string hides the paragraph.
    { title: 'Educational courses & LMS platform', image: 'educational-courses-and-lms-platform', tint: '#e2f6d5', description: '',
      features: ['Website & Learning Management System', 'User Dashboard for Learners', 'Search & AI-Powered Recommendations', 'VR Content Access for Immersive Learning'] },
    { title: 'Storyboard creation for films with AI', image: 'storyboard-creation-for-films-with-ai', tint: '#e9e2ff',
      description: 'It is a cutting-edge platform designed to transform the storyboard creation process using generative AI and advanced algorithms. This innovative tool allows filmmakers, advertisers, and content creators to convert scripts into stunning visual storyboards within minutes. It analyzes scripts, breaks them down scene by scene, and provides powerful editing tools to ensure narrative coherence and creative control.',
      features: ['Script to Storyboard Conversion', 'Effortless Iteration', 'Context Consistency & Creative Control', 'Intuitive Editing Tools'] },
    { title: 'Insurance management platform', image: 'insurance-management-platform', tint: '#dfe6ff',
      description: 'Introducing InsureTech, the ultimate cross-platform Flutter application designed to revolutionize insurance management. With its sleek and modern UI, users can seamlessly store and access all their insurance details in one centralized hub. Gone are the days of missing premium due dates. InsureTech keeps users informed with timely notifications, ensuring they never overlook important payments or coverage updates. From health to auto and everything in between, users can effortlessly manage all types of insurances within this powerful app.',
      features: ['Centralized Insurance Hub, User-Friendly, Modern UI', 'Timely Notifications, Easy Coverage Updates', 'Automatic Payment Reminders'] },
    { title: 'Social media & social commerce platform', image: 'social-media-and-social-commerce-platform', tint: '#ffe8d6',
      description: 'It is a social media and social commerce platform where users can connect through shared interests like singing, dancing, sports, and more. Join community groups, share content, engage with others, and shop directly from peer-to-peer listings using in-app crypto wallets. With features like leaderboards, brand promotions, and a personalized user profile, It creates a dynamic space for creators, consumers, and brands to interact.',
      features: ['Community-Based Interaction, Content Sharing', 'In-App Messaging', 'Peer-to-Peer Marketplace, Crypto Wallet Integration', 'Leaderboards, Engaging & Rewarding Experience'] },
  ],

  services: [
    { id: 'ai', title: 'AI & ML',
      description: 'We build AI-powered solutions that transform data into insights, automate complex tasks, and drive smarter decisions. From predictive analytics to computer vision and generative AI, our systems help businesses innovate and scale with confidence.',
      items: ['Predictive Analytics & Forecasting', 'NLP & Conversational AI', 'Computer Vision & Image Processing', 'Generative Models & Content Synthesis', 'Recommendation Systems & Personalization', 'AI Dashboards & Insights'] },
    { id: 'web', title: 'Web / Mobile App / SaaS',
      description: 'We create scalable software and applications that deliver seamless user experiences and business value. From enterprise SaaS platforms to web and mobile apps, our solutions are built to perform, adapt, and grow with your needs.',
      items: ['Web App Development', 'Mobile App Development', 'Custom SaaS Development', 'Workflow Automation', 'API Development & System Integration', 'Progressive Web App (PWA)'] },
    { id: 'ecom', title: 'E commerce',
      description: 'We build intelligent eCommerce platforms that elevate shopping experiences, improve conversions, and drive growth. From multi-vendor marketplaces to subscription commerce and AI-powered personalization, our solutions help retailers thrive in the digital-first era.',
      items: ['D2C / Multi-Vendor Marketplace', 'AI-Powered Personalization & Recommendation', 'Subscription / Rental & Recurring Billing Models', 'Checkout, Payment & Fraud Protection', 'Inventory, Fulfillment & Logistics Integration', 'UI/UX for Storefront & Customer Experience'] },
    { id: 'cloud', title: 'Cloud',
      description: 'We design cloud architectures that ensure scalability, security, and resilience for modern businesses. From cloud migration to DevOps automation and disaster recovery, our services help you optimize performance and reduce costs.',
      items: ['Cloud Migration & Modernization', 'Cloud Native App Development', 'Multi-Cloud & Hybrid Cloud Architecture', 'Cloud Security, Compliance & Governance', 'Observability, Monitoring & Performance Optimization', 'Disaster Recovery, Backup & Business Continuity'] },
  ],

  // Tools & technologies: the AI & ML category (grouped, with roles). `icon` names a file in public/assets/img/tech.
  stack: {
    heading: 'Connected intelligence, built for production',
    lead: 'How Demaze connects foundation AI models, orchestration frameworks, and real-time data infrastructure into resilient production software.',
    groups: ['AI Models', 'Orchestration', 'Data & ML', 'Streaming & Search'],
    items: [
      { name: 'OpenAI', role: 'Large Language Models', group: 'AI Models', icon: 'ai-openai' },
      { name: 'Hugging Face', role: 'Open-Source AI Models', group: 'AI Models', icon: 'ai-hugging-face' },
      { name: 'LangChain', role: 'LLM Orchestration', group: 'Orchestration', icon: 'ai-langchain' },
      { name: 'Python', role: 'Core AI & APIs', group: 'Orchestration', icon: 'ai-python' },
      { name: 'TensorFlow', role: 'Machine Learning Models', group: 'Data & ML', icon: 'ai-tensorflow' },
      { name: 'Pinecone Database', role: 'Vector Database', group: 'Data & ML', icon: 'ai-pinecone-database' },
      { name: 'Apache Kafka', role: 'Real-Time Streaming', group: 'Streaming & Search', icon: 'ai-apache-kafka' },
      { name: 'Elasticsearch', role: 'Search & Indexing', group: 'Streaming & Search', icon: 'ai-elasticsearch' },
    ],
  },

  // Every tab of "Tools & Technologies" on the live /services page. slug = Simple Icons slug (null = text only).
  tools: [
    { tab: 'AI & ML', items: [['Langchain', 'langchain'], ['Python', 'python'], ['Tensorflow', 'tensorflow'], ['OpenAI', null], ['Hugging Face', 'huggingface'], ['Pinecone Database', null], ['Apache Kafka', 'apachekafka'], ['Elastic Search', 'elasticsearch']] },
    { tab: 'Web', items: [['React.js', 'react'], ['Next.js', 'nextdotjs'], ['HTML5', 'html5'], ['CSS', 'css'], ['JavaScript', 'javascript'], ['TypeScript', 'typescript'], ['Redux', 'redux'], ['Tailwind CSS', 'tailwindcss'], ['Node.js', 'nodedotjs'], ['Nest.js', 'nestjs'], ['Express.js', 'express'], ['Elastic Search', 'elasticsearch'], ['MongoDB', 'mongodb'], ['Redis', 'redis']] },
    { tab: 'Mobile App', items: [['Flutter', 'flutter'], ['React Native', 'react'], ['Node.js', 'nodedotjs'], ['Nest.js', 'nestjs'], ['Express.js', 'express'], ['MongoDB', 'mongodb'], ['PostgreSQL', 'postgresql'], ['Redis', 'redis'], ['Firebase', 'firebase'], ['Docker', 'docker']] },
    { tab: 'UI/UX', items: [['Figma', 'figma'], ['Adobe XD', 'adobexd'], ['Photoshop', 'adobephotoshop'], ['Illustrator', 'adobeillustrator'], ['Sketch', 'sketch'], ['InVision', 'invision'], ['Marvel', 'marvelapp'], ['Zeplin', 'zeplin'], ['Balsamiq', 'balsamiq'], ['Axure RP', 'axure']] },
    { tab: 'eCommerce', items: [['React.js', 'react'], ['Next.js', 'nextdotjs'], ['Node.js', 'nodedotjs'], ['Nest.js', 'nestjs'], ['Express.js', 'express'], ['MongoDB', 'mongodb'], ['PostgreSQL', 'postgresql'], ['MySQL', 'mysql'], ['Redis', 'redis'], ['Elastic Search', 'elasticsearch'], ['AWS', 'amazonwebservices'], ['GCP', 'googlecloud'], ['Heroku', 'heroku'], ['Azure', 'microsoftazure'], ['Hostinger', 'hostinger']] },
    { tab: 'Cloud', items: [['AWS', 'amazonwebservices'], ['GCP', 'googlecloud'], ['Azure', 'microsoftazure'], ['Docker', 'docker'], ['Kubernetes', 'kubernetes'], ['Terraform', 'terraform'], ['Jenkins', 'jenkins'], ['Github', 'github'], ['Postman', 'postman'], ['JMeter', 'apachejmeter'], ['Selenium', 'selenium'], ['Vultr', 'vultr'], ['Digital Ocean', 'digitalocean'], ['Heroku', 'heroku'], ['Apache Kafka', 'apachekafka'], ['Redis', 'redis'], ['Elastic Search', 'elasticsearch']] },
  ],

  industries: [
    ['Healthcare', ['Telemedicine Platforms', 'Electronic Health Records (EHR)', 'Patient Management Systems', 'Appointment Scheduling Software', 'Healthcare Analytics Platforms', 'Wellness Tracking Applications', 'Medical Device Integration', 'Hospital Management Systems']],
    ['Fintech', ['Digital Payment Platforms', 'Mobile Banking Applications', 'Cryptocurrency Wallets', 'Peer-to-Peer Payment Systems', 'Lending Management Software', 'Credit Scoring Systems', 'Financial Analytics Tools', 'Blockchain Payment Solutions', 'Trading Platform Development']],
    ['Logistics', ['Delivery Management Systems', 'Shipping Logistics Management', 'Fleet Management Software', 'Inventory Management Software', 'Telematics Software Development', 'Warehouse Management Systems', 'Route Optimization Platforms', 'Supply Chain Visibility Tools', 'Last-Mile Delivery Solutions']],
    ['Retail', ['Point-of-Sale (POS) Systems', 'Inventory Management Platforms', 'Customer Loyalty Programs', 'Staff Management Software', 'Omnichannel Retail Solutions', 'Price Management Systems', 'Retail Analytics Dashboards', 'Store Operations Management', 'Customer Relationship Management']],
    ['Ecommerce', ['Multi-Vendor Marketplaces', 'B2B Ecommerce Platforms', 'B2C Online Stores', 'Shopping Cart Development', 'Payment Gateway Integration', 'Product Recommendation Engines', 'Order Management Systems', 'Customer Review Platforms', 'Auction & Bidding Systems']],
    ['Education', ['Learning Management Systems (LMS)', 'Online Course Platforms', 'Virtual Classroom Software', 'Student Information Systems', 'Assessment & Testing Platforms', 'Educational Content Management', 'VR Learning Applications', 'AI-Powered Tutoring Systems', 'Certification Management']],
    ['BFSI Solutions', ['Core Banking Systems', 'Insurance Management Platforms', 'Loan Origination Systems', 'Credit Monitoring Software', 'Regulatory Compliance Tools', 'Risk Management Systems', 'Customer Onboarding Solutions', 'Anti-Money Laundering (AML) Tools', 'Investment Portfolio Management']],
    ['Sports & Gaming', ['Fantasy Sports Platforms', 'Gaming Applications', 'Tournament Management Systems', 'Live Streaming Applications', 'Sports Analytics Platforms', 'Community Gaming Solutions', 'Leaderboard Systems', 'In-Game Payment Solutions', 'Sports Betting Platforms']],
    ['Energy & Utility', ['Smart Grid Management', 'Energy Monitoring Systems', 'Utility Billing Platforms', 'Renewable Energy Management', 'Consumption Analytics Tools', 'IoT Sensor Integration', 'Energy Trading Platforms', 'Grid Optimization Software', 'Meter Data Management']],
    ['Real Estate', ['Property Management Systems', 'Virtual Tour Platforms', 'Real Estate CRM Solutions', 'Rental Management Applications', 'Property Listing Websites', 'Automated Valuation Models', 'Property Investment Platforms', 'Facility Management Software', 'Real Estate Analytics Tools']],
    ['Media & Entertainment', ['Content Management Systems', 'Streaming Platforms', 'Digital Asset Management', 'Social Media Applications', 'Video Processing Tools', 'AI Content Creation Platforms', 'Live Broadcasting Solutions', 'Creative Collaboration Tools', 'Subscription Management Systems']],
    ['SaaS Products', ['Multi-Tenant Applications', 'Subscription Management Systems', 'Cloud-Native Platforms', 'API Development & Integration', 'Analytics Dashboard Solutions', 'Customer Success Platforms', 'Workflow Automation Tools', 'Data Management Systems', 'Enterprise Software Solutions']],
    ['Automotive', ['Dealership Management Systems', 'Vehicle Valuation Tools', 'Service Scheduling Platforms', 'Car Rental Management', 'Fleet Tracking Systems', 'Automotive CRM Solutions', 'Parts Inventory Management', 'Customer Engagement Platforms', 'Vehicle Financing Calculators']],
    ['Food & Beverage', ['Food Delivery Platforms', 'Restaurant Management Systems', 'Kitchen Display Systems', 'Menu Management Software', 'Food Safety Compliance Tools', 'Inventory Tracking Systems', 'Customer Ordering Apps', 'Multi-Vendor Food Marketplaces', 'Recipe Management Systems']],
    ['Legal & Professional Services', ['Case Management Systems', 'Document Automation Tools', 'Legal Practice Management', 'Time & Billing Software', 'Client Portal Systems', 'Contract Management Solutions', 'Compliance Tracking Tools', 'Legal Research Platforms', 'Court Filing Systems']],
    ['Human Resources', ['Applicant Tracking Systems', 'Employee Onboarding Platforms', 'Performance Management Tools', 'Payroll Management Systems', 'Workforce Analytics Solutions', 'Employee Self-Service Portals', 'Talent Acquisition Platforms', 'HR Compliance Software', 'Learning & Development Systems']],
    ['Insurance', ['Policy Management Systems', 'Claims Processing Automation', 'Insurance CRM Solutions', 'Premium Calculation Tools', 'Underwriting Software', 'Customer Self-Service Portals', 'Insurance Mobile Applications', 'Risk Assessment Tools', 'Regulatory Reporting Systems']],
    ['Social Commerce', ['Social Media Platforms', 'Peer-to-Peer Marketplaces', 'Community Management Systems', 'Social Shopping Applications', 'Influencer Marketing Platforms', 'User-Generated Content Systems', 'Social Analytics Tools', 'Crypto Wallet Integration', 'Social Gaming Features']],
    ['Manufacturing & B2B', ['Supply Chain Management', 'Vendor Management Platforms', 'Procurement Automation Systems', 'Manufacturing Execution Systems', 'Quality Management Software', 'Business Intelligence Dashboards', 'B2B Marketplace Development', 'Production Planning Tools', 'Equipment Maintenance Systems']],
  ],

  whyUs: [
    { title: 'AI-First Innovation',
      description: "We don't just build software; we create intelligent solutions that learn, adapt, and evolve. Our deep expertise in AI, machine learning, and emerging technologies ensures your business stays ahead of the curve with future-ready solutions that drive automation and growth." },
    { title: 'End-to-End Partnership',
      description: "From concept to deployment and beyond, we're your dedicated tech partner. We work as an extension of your team, providing comprehensive support across the entire development lifecycle while focusing on long-term success rather than just project delivery." },
    { title: 'Proven Track Record',
      description: 'With 45+ successful projects across diverse industries and $10M+ generated for our clients, we bring measurable results. Our experienced team of 35+ professionals combines technical excellence with business acumen to deliver solutions that create real impact.' },
  ],

  about: {
   
    whoWeAre: [
      "At Demaze Technologies, we're more than just developers; we're digital transformation architects. We're a passionate team of 35+ technologists, innovators, and strategic thinkers who believe in the power of AI and cutting-edge technology to reshape businesses.",
      'Founded with a vision to democratize advanced technology, we bridge the gap between complex technical possibilities and real business outcomes.',
    ],
    drives: [
      { title: 'Innovation at Our Core', description: "We're driven by the challenge of turning ambitious ideas into reality. Every project is an opportunity to push boundaries and create something extraordinary that makes a meaningful impact." },
      { title: 'Client Success Obsession', description: "Your success is our success. We're motivated by seeing our clients achieve breakthrough results, streamline operations, and unlock new growth opportunities through the solutions we build together." },
      { title: 'Technology for Good', description: 'We believe technology should empower, simplify, and enhance human potential. This drives us to create solutions that not only solve problems but also open new possibilities for businesses and their customers.' },
      { title: 'Continuous Learning', description: "In a rapidly evolving tech landscape, we're driven by curiosity and the pursuit of excellence. We constantly evolve our skills and adopt emerging technologies to deliver the most advanced solutions." },
    ],
  },

  process: [
    { title: 'Discover & Define', description: 'We start by understanding your vision, challenges, and goals. Through deep discovery workshops and research, we define clear requirements and success metrics.' },
    { title: 'Design & Prototype', description: 'Ideas take shape with user-focused designs and interactive prototypes. This ensures alignment, clarity, and a shared vision before development begins.' },
    { title: 'Build & Integrate', description: 'Our engineering team develops scalable, secure, and high-performance solutions. We follow agile methods, ensuring continuous feedback and seamless system integration.' },
    { title: 'Launch & Scale', description: 'Once tested and refined, we launch with confidence. Beyond delivery, we support you in scaling, optimizing, and evolving the product for long-term growth.' },
  ],

  faq: [
    { q: 'What makes Demaze different from other development companies?', a: "We're an AI-first technology partner, not just a development service provider. Unlike traditional companies that focus on coding, we specialize in intelligent solutions that leverage cutting-edge AI, machine learning, and automation. We work as an extension of your team, focusing on long-term partnerships and measurable business outcomes rather than just project delivery." },
    { q: 'How long does it typically take to develop a custom solution?', a: 'Project timelines vary based on complexity and requirements, but most custom solutions take 3-6 months from concept to deployment. Simple applications may take 6-12 weeks, while complex AI-powered platforms or enterprise solutions can take 6-12 months. We provide detailed project timelines during our initial consultation and maintain transparent communication throughout the development process.' },
    { q: 'Do you work with startups or only established enterprises?', a: 'We work with both startups and established enterprises across various industries. Our scalable approach allows us to support early-stage companies with MVP development and growth-stage businesses with comprehensive digital transformation. We tailor our solutions and engagement models to match your business size, budget, and growth objectives.' },
    { q: 'What ongoing support do you provide after project completion?', a: 'We offer comprehensive post-launch support including maintenance, updates, performance monitoring, and technical assistance. Our support packages range from basic maintenance to full managed services with dedicated support teams. We also provide training for your team and can scale our support based on your evolving needs as your business grows.' },
    { q: 'How do you ensure the security and confidentiality of our project?', a: 'Security and confidentiality are paramount in everything we do. We implement industry-standard security protocols, sign comprehensive NDAs before any project discussion, follow secure development practices, and ensure data protection compliance (GDPR, CCPA, etc.). All our team members are bound by strict confidentiality agreements, and we use secure development environments and encrypted communication channels.' },
  ],

  // Motion reels on the projects page (public/assets/reel.js, reel-kit.js, reel3d.js), keyed by project image.
  // Each reel tells the project as a short story: title → the brief → the product (hero) → one chapter per
  // capability, in the order a user meets them → the outcome → sign-off. Its length follows from the chapters
  // (a scene may set `dur`). The brief and outcome paraphrase the project's own description; labels come from
  // its description, features or app screens. Chat lines, chart shapes, prices and map routes are illustrative,
  // not client data. `art` names are files in public/assets/img/reel/ (Fluent 3D renders); scene types are
  // listed in reel-kit.js. Car heroes use the SUV studio renders (model: 'gls', a graphite Mercedes-Benz GLS, or 'rrs', a
  // debadged pearl Range Rover Sport); other heroes are 3D. Headlines put their last word or two in the project colour
  // (a scene can set `accent` to the number of words).
  // Each reel has its own `look` (studio, noir, paper, blueprint, tint, dots), `move` between chapters (push, slide,
  // cut, wipe) and optional `align: 'left'`, so neighbouring cards never feel like the same film. Car heroes tell one
  // of two stories: the showroom start-up (default) or `story: 'service'` (drive-in, scan, job card). Dashboards have
  // one screen per sidebar tab in `views` (table, bars, line or donut); every figure in them is illustrative.
  reels: {
    'ai-based-software-for-luxury-car-dealers': {
      name: 'Carzup', look: 'noir', move: 'push', tagline: 'AI software for luxury car dealers', client: "Built for one of India's largest luxury car dealerships",
      brief: { text: 'One system to value used cars, quote new-car EMIs, run refurbishment and back the sales team.',
        items: [{ label: 'Valuations', art: 'car' }, { label: 'EMIs', art: 'card' }, { label: 'Refurbishment', art: 'tools' }, { label: 'Sales', art: 'office2' }] },
      hero: { kind: 'car', model: 'gls', chapter: 'Valuation', cap: 'A trade-in arrives and is valued accurately',
        tags: ['Model year 2018', '1,00,000 km', 'Diesel'], value: { to: 5000000, prefix: '₹ ', format: 'inr', label: 'AI valuation' },
        marks: [['Condition', 'front'], ['Bodywork', 'body'], ['Tyres', 'rear']] },
      scenes: [
        // EMI per month across tenures, normalised (shape only, not a quote).
        { type: 'bars', chapter: 'New car EMI', cap: 'The customer sees instant EMIs for a new car', art: 'suv', artLabel: 'Monthly EMI', readout: ['₹4,44,000', '₹2,32,000', '₹1,61,500', '₹1,26,700', '₹1,05,500'], sub: ['12 months', '24 months', '36 months', '48 months', '60 months'], display: ['₹4.4L', '₹2.3L', '₹1.6L', '₹1.3L', '₹1.1L'],
          labels: ['12', '24', '36', '48', '60'], values: [1, 0.522, 0.364, 0.285, 0.237] },
        { type: 'checklist', chapter: 'Refurbishment', cap: 'The trade-in is refurbished, step by step', art: 'car', items: [{ label: 'Inspection', art: 'search' }, { label: 'Bodywork', art: 'tools' }, { label: 'Paint', art: 'palette' }, { label: 'Ready to sell', art: 'sparkle' }] },
        { type: 'pipeline', chapter: 'Tracking', cap: 'Every car is tracked from trade-in to sale', stages: ['Valued', 'Refurbishing', 'Listed', 'Sold'], counts: [6, 4, 9, 3], card: { label: 'Trade-in', art: 'car' }, ghosts: ['suv', 'car'] },
        { type: 'hub', chapter: 'Sales backend', cap: 'Every team works from the same backend', center: 'Carzup', centerArt: 'car', nodes: [{ label: 'Sales consultant', art: 'office2' }, { label: 'Used cars', art: 'car' }, { label: 'Service advisor', art: 'mechanic' }, { label: 'Admin', art: 'office' }, { label: 'Tech support', art: 'person3' }] },
        { type: 'dashboard', chapter: 'Overview', cap: 'Managers see every deal in one place', title: 'Carzup', nav: ['Valuations', 'EMI', 'Refurb', 'Sales'],
          // one screen per tab; figures are illustrative
          views: [
            { kind: 'table', kpis: [['128', 'Valuations', 'This month'], ['₹38.4L', 'Avg. value', 'Used cars'], ['96%', 'Accuracy', 'vs. final sale']],
              rows: [['Trade-in #1042', 'BMW X5 · 2018', 'Valuing', 'Valued'], ['Trade-in #1043', 'Audi Q7 · 2019', 'Inspecting', 'Valued'], ['Trade-in #1038', 'GLS 450 · 2020', 'Sold']] },
            { kind: 'bars', kpis: [['342', 'EMI quotes', 'This month'], ['₹1,26,700', 'Avg. EMI', '48 months'], ['71%', 'Approved', 'By lenders']],
              labels: ['12 mo', '24 mo', '36 mo', '48 mo', '60 mo'], values: [4.44, 2.32, 1.62, 1.27, 1.06], display: ['₹4.4L', '₹2.3L', '₹1.6L', '₹1.3L', '₹1.1L'] },
            { kind: 'donut', kpis: [['23', 'In refurb', 'Cars'], ['6.5 days', 'Turnaround', 'Average'], ['₹42,000', 'Avg. cost', 'Per car']], center: '23 cars',
              parts: [['Bodywork', 38], ['Paint', 27], ['Mechanical', 22], ['Detailing', 13]] },
            { kind: 'line', kpis: [['₹4.2Cr', 'Revenue', 'This quarter'], ['64', 'Cars sold', '+18%'], ['12 days', 'To sell', 'Average']],
              labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], values: [2.1, 2.6, 2.4, 3.1, 3.6, 4.2], fmt: ['₹', 'Cr', 1] },
          ] },
      ],
      outcome: { text: 'Smoother operations for the dealership and a better experience for every customer.', items: ['Accurate valuations', 'Instant EMIs', 'Tracked refurbishment'] },
      outro: 'Four tools · one dealership',
    },
    'investigative-case-management-software': {
      name: 'Case Files', look: 'paper', move: 'cut', align: 'left', tagline: 'AI tools for private investigators', accent: '#2bb3a3',
      brief: { text: 'Give private investigators one secure place to organise cases, analyse media and automate the paperwork, from anywhere.',
        items: [{ label: 'Cases', art: 'folder' }, { label: 'Media', art: 'camera' }, { label: 'Documents', art: 'doc' }, { label: 'Security', art: 'lock' }] },
      hero: { kind: 'laptop', opts: { screen: { web: true, accent: '#2bb3a3', title: 'Cases', nav: ['Case board', 'Media', 'Documents', 'Workflows'], tiles: [['Cases', 'Organised'], ['Media', 'Stored'], ['Tasks', 'Automated']] } },
        chapter: 'The platform', title: 'Case management', cap: 'Case management in the browser, from anywhere', tags: ['Case information', 'Media', 'Secure storage'] },
      scenes: [
        { type: 'board', chapter: 'Organise', cap: 'Every case, its media and leads pinned together', items: [{ label: 'Case file', art: 'folder' }, { label: 'Photos', art: 'photo' }, { label: 'Location', art: 'pin' }, { label: 'Video', art: 'video' }, { label: 'Notes', art: 'memo' }, { label: 'Witness', art: 'detective' }] },
        { type: 'products', chapter: 'AI tools', cap: 'AI tools analyse photos, video and documents', query: 'Find matches in case media', ai: true, pick: 1, badge: 'AI match', items: [{ art: 'photo', label: 'Photo', sub: 'Tagged' }, { art: 'video', label: 'Video', sub: 'Matched' }, { art: 'doc', label: 'Document', sub: 'Summarised' }] },
        { type: 'flow', chapter: 'Workflows', cap: 'Automated workflows move each case forward', steps: [{ label: 'New case', art: 'folder' }, { label: 'AI review', art: 'ai' }, { label: 'Report', art: 'clipboard' }] },
        { type: 'document', chapter: 'Documents', cap: 'Case reports are generated automatically', title: 'Case Report', stamp: 'Generated', exports: ['pdf'], fields: [['Case', '#CF-2291'], ['Client', 'A. Kapoor'], ['Subject', 'Asset trace'], ['Evidence', '14 photos · 3 videos'], ['Status', 'Findings ready']] },
        { type: 'transfer', chapter: 'Billing', cap: 'Subscriptions paid by automatic deposit', from: { label: 'Subscription', sub: 'Monthly plan', art: 'card' }, to: { label: 'Auto deposit', sub: 'Processed', art: 'bank' }, token: 'coin' },
        { type: 'devices', chapter: 'Security', cap: 'Web-based access, with data kept secure', label: 'Secure data storage', art: 'lock' },
      ],
      outcome: { text: 'Investigators get AI-powered tools and every case organised, secured and reachable anywhere.', items: ['Organised cases', 'Automated paperwork', 'Secure storage'] },
      outro: 'Case work, organised',
    },
    'ai-powered-luxury-ecommerce-platform': {
      name: 'Eco Chic', look: 'studio', move: 'slide', tagline: 'Sustainable luxury fashion', accent: '#2f7a5d',
      brief: { text: 'A premium store for sustainable luxury, where every piece can be bought, rented or resold.',
        items: [{ label: 'Shop', art: 'bagshop' }, { label: 'Rent', art: 'dress' }, { label: 'Resell', art: 'recycle' }, { label: 'Authenticate', art: 'gem' }] },
      hero: { kind: 'bag', opts: { color: '#1f5c46', label: 'ECO CHIC' }, chapter: 'The store', title: 'Eco Chic', cap: 'A premium, sustainable luxury store', tags: ['Shop', 'Rent', 'Sell'] },
      scenes: [
        { type: 'products', chapter: 'Search', cap: 'AI search understands what shoppers mean', query: 'Linen coat, sustainable', ai: true, pick: 0, badge: 'Best match', items: [{ art: 'blazer', label: 'Linen coat', sub: 'Pre-loved' }, { art: 'dress', label: 'Midi dress', sub: 'New in' }, { art: 'handbag', label: 'Leather bag', sub: 'Authenticated' }, { art: 'heel', label: 'Heels', sub: 'Rent it' }] },
        { type: 'tryon', chapter: 'Try-on', cap: 'Virtual try-ons before anything ships', label: 'AI stylist', looks: [{ art: 'dress', label: 'Midi dress', hue: -70, color: '#2f7a5d' }, { art: 'blazer', label: 'Linen coat', color: '#cfa982' }, { art: 'kimono', label: 'Silk kimono', color: '#3b6fd8' }] },
        { type: 'carousel', chapter: 'For you', cap: 'Recommendations tuned to each shopper', title: 'Picked for you', items: [{ art: 'handbag', label: 'Bags' }, { art: 'sunglasses', label: 'Eyewear' }, { art: 'watch', label: 'Watches' }, { art: 'heel', label: 'Shoes' }, { art: 'scarf', label: 'Scarves' }, { art: 'ring', label: 'Jewellery' }] },
        { type: 'pricing', chapter: 'Price models', cap: 'AI prices every piece to buy, rent or resell', art: 'handbag', label: 'Designer bag', options: [['Buy', 'Own it', '$2,450'], ['Rent', 'Wear it for a week', '$180'], ['Resell', 'Pre-loved resale', '$1,390']] },
        { type: 'live', chapter: 'Live selling', cap: 'Live selling turns a stream into orders', art: 'handbag', label: 'Leather bag', cta: 'Buy', host: 'person2', feed: ['Is it in green?', 'Just bought one!', 'Love the stitching'] },
        { type: 'passport', chapter: 'Authentication', cap: 'Each piece carries a digital passport', art: 'handbag', label: 'Designer bag', result: 'Authenticated', sub: 'Digital passport' },
        { type: 'flow', chapter: 'Automation', cap: 'Orders are processed and dispatched automatically', steps: [{ label: 'Order in', art: 'bagshop' }, { label: 'Automated', art: 'gear' }, { label: 'Dispatched', art: 'truck' }] },
        { type: 'inventory', chapter: 'Inventory', cap: 'Smart stock control restocks before items run out', order: 'Order packed', items: [{ art: 'dress', label: 'Dresses' }, { art: 'handbag', label: 'Bags' }, { art: 'heel', label: 'Shoes' }, { art: 'watch', label: 'Watches' }] },
        { type: 'cms', chapter: 'CMS', cap: 'The team builds pages with drag and drop', title: 'Home page', blocks: ['Hero banner', 'New arrivals', 'AI stylist'] },
        { type: 'dashboard', chapter: 'Analytics', cap: 'AI-powered analytics across sales, rentals and resale', title: 'Eco Chic admin', nav: ['Dashboard', 'Products', 'Orders', 'CMS'],
          views: [
            { kind: 'line', kpis: [['$184K', 'Sales', 'This month'], ['1,240', 'Rentals', 'Active'], ['386', 'Resale', 'Listed']],
              labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], values: [92, 108, 121, 139, 162, 184], fmt: ['$', 'K', 0] },
            { kind: 'donut', kpis: [['2,480', 'Products', 'Live'], ['312', 'Pre-loved', 'Authenticated'], ['48', 'New in', 'This week']], center: '2,480 pieces',
              parts: [['Dresses', 34], ['Bags', 26], ['Shoes', 22], ['Jewellery', 18]] },
            { kind: 'table', kpis: [['1,905', 'Orders', 'This month'], ['98.2%', 'On time', 'Dispatched'], ['2.1 days', 'Delivery', 'Average']],
              rows: [['#EC-4821', 'Linen coat · Buy', 'Packed', 'Shipped'], ['#EC-4822', 'Midi dress · Rent', 'Shipped', 'Delivered'], ['#EC-4819', 'Leather bag · Resell', 'Delivered']] },
            { kind: 'bars', kpis: [['24', 'Pages', 'Published'], ['6', 'Drafts', 'In review'], ['3.4%', 'Conversion', 'Home page']],
              labels: ['Home', 'New in', 'Rent', 'Resale', 'Journal'], values: [48, 31, 26, 19, 12], display: ['48K', '31K', '26K', '19K', '12K'] },
          ] },
      ],
      outcome: { text: 'A scalable, user-friendly store built for innovation and environmental responsibility.', items: ['Personalised journeys', 'Circular fashion', 'Secure data'] },
      outro: 'Luxury, made circular',
    },
    'senior-engagement-and-support-platform': {
      name: 'Sukoon', look: 'paper', move: 'wipe', tagline: 'Community for seniors, by seniors', accent: '#e0a200', client: 'Sukoon Unlimited',
      brief: { text: 'Help seniors lead connected, purposeful lives, with support, conversation and activities that reduce isolation.',
        items: [{ label: 'Companions', art: 'senior' }, { label: 'Coaching', art: 'chat' }, { label: 'Meetups', art: 'calendar' }, { label: 'Stories', art: 'book' }] },
      hero: { kind: 'phone', opts: { accent: '#f5b50a', screen: { accent: '#e9a800', title: 'Sukoon', items: [['Sarathis', 'Trusted companions'], ['Club Sukoon', 'Activities'], ['Coaching', 'Personalised'], ['Meetups', 'Social'], ['Sukoon Corner', 'Blog']] } },
        chapter: 'The app', title: 'Sukoon', cap: 'Everything a member needs, in one app', tags: ['Sarathis', 'Club Sukoon', 'Coaching'] },
      scenes: [
        { type: 'call', chapter: 'Sarathis', cap: 'A member speaks with a Sarathi, a trusted companion', note: 'Available 9 AM – 9 PM', people: [{ art: 'senior', label: 'Member' }, { art: 'person2', label: 'Sarathi' }] },
        { type: 'chat', chapter: 'Coaching', cap: 'Personalised coaching and counselling', title: 'Coaching session', status: 'Coach online', people: ['person2', 'senior'], messages: [['in', 'How are you feeling today?'], ['out', 'Much better, thank you'], ['in', 'Shall we plan your next session?'], ['out', 'Yes please, Thursday?']] },
        { type: 'hub', chapter: 'Club Sukoon', cap: 'Club Sukoon brings compassionate people together', center: 'Club Sukoon', centerArt: 'heart', nodes: [{ label: 'Members', art: 'senior' }, { label: 'Sarathis', art: 'person2' }, { label: 'Coaches', art: 'teacher' }, { label: 'Friends', art: 'senior2' }, { label: 'Volunteers', art: 'person3' }] },
        { type: 'calendar', chapter: 'Meetups', cap: 'Meetups and social events to join', month: 'Meetups', day: 18, event: 'Community meetup', sub: 'Share experiences, make friends', art: 'hands' },
        { type: 'cards', chapter: 'Sukoon Corner', cap: 'The Sukoon Corner blog shares stories and guidance', items: [{ art: 'book', title: 'Stories', sub: 'Shared by members' }, { art: 'chat', title: 'Guidance', sub: 'Advice from peers' }, { art: 'heart', title: 'Well-being', sub: 'Enriching discussions', chip: 'New' }] },
        { type: 'stats', chapter: 'Impact', cap: 'Loved by the seniors it serves', items: [{ to: 95, suffix: '%', label: 'Seniors loved Sukoon', ring: 0.95 }, { to: 4.8, dec: 1, label: 'Conversation score', ring: 0.96 }, { to: 10, suffix: '+', label: 'Languages supported', ring: 1 }] },
      ],
      outcome: { text: 'A dedicated space where seniors share experiences, seek guidance and feel connected.', items: ['Less isolation', 'Meaningful conversations', 'Emotional well-being'] },
      outro: 'Reducing isolation, fostering connection',
    },
    'multi-vendor-ecommerce-marketplace': {
      name: 'Better That', look: 'tint', move: 'slide', align: 'left', tagline: 'You shop, we give back', accent: '#ef5b3f',
      brief: { text: "Australia and New Zealand's marketplace where shoppers, retailers and good causes all do better.",
        items: [{ label: 'Shoppers', art: 'bagshop' }, { label: 'Retailers', art: 'store' }, { label: 'Good causes', art: 'heart' }, { label: 'Brands', art: 'tag' }] },
      hero: { kind: 'phone', opts: { accent: '#f3c3bb', screen: { accent: '#ef5b3f', title: 'better that.', items: [['Women', 'Shop by category'], ['Shoes', 'Latest trends'], ['Dresses', 'New in'], ['Accessories', 'Brands'], ['Wishlist', 'Saved']] } },
        chapter: 'The app', title: 'Better That', cap: 'The latest trends, shoes, dresses and accessories', tags: ['Trends', 'Shoes', 'Dresses', 'Accessories'] },
      scenes: [
        { type: 'products', chapter: 'Browse', cap: 'Shoppers browse by category or just search', query: 'Summer dresses', pick: 0, badge: 'Trending', items: [{ art: 'dress', label: 'Dresses', sub: 'Latest trends' }, { art: 'sneaker', label: 'Shoes', sub: 'New in' }, { art: 'sunglasses', label: 'Accessories', sub: 'Brands' }, { art: 'handbag', label: 'Bags', sub: 'Wishlist' }] },
        { type: 'auction', chapter: 'Drop auction', cap: 'Live drop auctions: the price falls until someone buys', art: 'watch', label: 'Designer watch', title: 'Price dropping', currency: 'A$', from: 240, to: 129, stamp: 'Won' },
        { type: 'currency', chapter: 'Currency', cap: 'Prices convert between Australian and New Zealand dollars', from: 'AUD', fromLabel: 'Australia', to: 'NZD', toLabel: 'New Zealand', amount: 129, rate: 1.09 },
        { type: 'flow', chapter: 'Checkout', cap: 'Wishlist, bag and many ways to pay', steps: [{ label: 'Wishlist', art: 'heart' }, { label: 'Add to bag', art: 'bagshop' }, { label: 'Pay your way', art: 'card' }] },
        { type: 'transfer', chapter: 'Giving back', cap: 'Every purchase gives back to a good cause', from: { label: 'Your order', sub: 'Checked out', art: 'bagshop' }, to: { label: 'Good cause', sub: 'Donation sent', art: 'hands' }, token: 'heart' },
        { type: 'hub', chapter: 'Retailers', cap: 'Retailers reach more shoppers through one marketplace', center: 'Better That', centerArt: 'bagshop', nodes: [{ label: 'Shoppers', art: 'person2' }, { label: 'Good causes', art: 'heart' }, { label: 'Retailers', art: 'store' }, { label: 'Brands', art: 'tag' }] },
      ],
      outcome: { text: 'A faster, better shopping experience and more reach for every retailer.', stat: { to: 99, suffix: '%', label: 'Lighthouse score' }, items: ['Multi-vendor', 'Live auctions', 'Giving back'] },
      outro: 'Shopping made better',
    },
    'multi-shoppers-food-and-grocery-delivery-app': {
      name: 'Local Shops', look: 'dots', move: 'push', align: 'left', tagline: 'Local stores, selling online', accent: '#2e9e4f',
      brief: { text: 'Help local shops sell online and run their digital stores, from the first order to the doorstep.',
        items: [{ label: 'Grocery', art: 'apple' }, { label: 'Household', art: 'basket' }, { label: 'Restaurants', art: 'takeout' }, { label: 'Delivery', art: 'scooter' }] },
      hero: { kind: 'phone', opts: { accent: '#f6c945', screen: { accent: '#2e9e4f', title: 'Deliver to Office', items: [['Grocery', 'Fresh & daily'], ['Household', 'Essentials'], ['Restaurants', 'Food'], ['Best Supermarket', 'Nearby'], ['Orders', 'Track']] } },
        chapter: 'The app', title: 'Local Shops', cap: 'Grocery, household items and restaurant food', tags: ['Grocery', 'Household', 'Restaurant food'] },
      scenes: [
        { type: 'products', chapter: 'Order', cap: 'A customer orders from shops nearby', query: 'Fresh fruit', pick: 0, badge: 'Nearby', items: [{ art: 'apple', label: 'Fruit', sub: 'Grocery' }, { art: 'milk', label: 'Dairy', sub: 'Daily' }, { art: 'bread', label: 'Bakery', sub: 'Fresh' }, { art: 'carrot', label: 'Vegetables', sub: 'Local' }] },
        { type: 'apps', chapter: 'Three apps', cap: 'One app each for customers, sellers and riders', items: [{ label: 'User', job: 'Order', art: 'bagshop', color: '#2e9e4f', rows: ['Apples · 1 kg', 'Milk · 2 L', 'Bread'], done: 'Order placed' }, { label: 'Seller', job: 'Pack', art: 'store', color: '#f5a524', rows: ['Order #2291', 'Items picked', 'Bag sealed'], done: 'Ready' }, { label: 'Rider', job: 'Deliver', art: 'scooter', color: '#3d5afe', rows: ['Picked up', '1.2 km away', 'At the door'], done: 'Delivered' }] },
        { type: 'pipeline', chapter: 'Orders', cap: 'Every order is managed from packing to delivery', stages: ['Ordered', 'Packed', 'On the way', 'Delivered'], counts: [5, 3, 4, 12], card: { label: 'Order', art: 'basket' }, ghosts: ['apple', 'bread', 'milk'] },
        { type: 'map', chapter: 'Delivery', cap: 'Riders deliver inside each store’s delivery area', from: { label: 'Shop', art: 'store' }, to: { label: 'Home', art: 'house' }, vehicle: 'scooter', zones: true, eta: 'Arriving in 12 min', arrived: 'Delivered' },
        { type: 'inventory', chapter: 'Store control', cap: 'Shop owners keep full control of their digital store', order: 'Stock updated', items: [{ art: 'apple', label: 'Fruit' }, { art: 'milk', label: 'Dairy' }, { art: 'bread', label: 'Bakery' }, { art: 'cheese', label: 'Cheese' }] },
        { type: 'dashboard', chapter: 'Admin', cap: 'The React admin panel manages stores, riders and accounts', title: 'Admin panel', nav: ['Stores', 'Orders', 'Riders', 'Accounts'],
          views: [
            { kind: 'bars', kpis: [['142', 'Stores', 'Live'], ['38', 'New stores', 'This month'], ['4.7★', 'Rating', 'Average']],
              labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], values: [620, 710, 680, 790, 860, 1086] },
            { kind: 'table', kpis: [['1,086', 'Orders', 'Today'], ['24 min', 'Delivery', 'Door to door'], ['0.8%', 'Cancelled', 'Today']],
              rows: [['#LS-2291', 'Best Supermarket', 'Packed', 'On the way'], ['#LS-2292', 'Fresh Bakery', 'Ordered', 'Packed'], ['#LS-2287', 'Green Grocer', 'Delivered']] },
            { kind: 'donut', kpis: [['86', 'Riders', 'On shift'], ['12.4', 'Orders per rider', 'Today'], ['4.8★', 'Rider rating', 'Average']], center: '86 riders',
              parts: [['Delivering', 46], ['At store', 21], ['Idle', 18], ['Offline', 15]] },
            { kind: 'line', kpis: [['₹6.8L', 'Payouts', 'This week'], ['₹92,000', 'Commission', 'This week'], ['142', 'Settled', 'Stores']],
              labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], values: [0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.1], fmt: ['₹', 'L', 1] },
          ] },
      ],
      outcome: { text: 'A seamless experience for customers, with local shop owners in charge of their own stores.', items: ['Flutter apps', 'React admin', 'Delivery areas'] },
      outro: 'Local stores, online',
    },
    'car-service-and-customer-engagement-platform': {
      name: 'Car Service', look: 'blueprint', move: 'wipe', align: 'left', tagline: "For an authorised dealership's service department", accent: '#d64545',
      brief: { text: "Run an authorised dealership's service department on data: maintenance, repairs and body & paint.",
        items: [{ label: 'Maintenance', art: 'oil' }, { label: 'Repairs', art: 'wrench' }, { label: 'Body & paint', art: 'palette' }, { label: 'Customers', art: 'person3' }] },
      hero: { kind: 'car', model: 'rrs', story: 'service', chapter: 'Customer data', cap: 'Each car arrives with its customer record attached',
        // the service story: drive-in, diagnostic scan, checkpoints with their status, the customer's ticket
        ticketTitle: 'Job card #4521', ticket: [['Owner', 'R. Mehta'], ['Reg. no.', 'MH 12 AB 4521'], ['Last service', 'PM · 12 Mar'], ['Due now', 'GR check']],
        tags: ['Last service: PM', 'Due: GR check', 'Owner notified'], marks: [['Lights', 'head', 'OK'], ['Body & paint', 'body', 'OK'], ['Brakes', 'rear', 'Check']] },
      scenes: [
        { type: 'tiles', chapter: 'Services', cap: 'Three service lines: PM, GR and BP', items: [{ art: 'oil', label: 'PM', sub: 'Preventive maintenance' }, { art: 'wrench', label: 'GR', sub: 'General repairs' }, { art: 'palette', label: 'BP', sub: 'Body & paint' }] },
        { type: 'calendar', chapter: 'Reminders', cap: 'Service reminders go out automatically', month: 'Service due', day: 22, event: 'Service reminder', sub: 'Sent automatically', art: 'bell' },
        { type: 'notify', chapter: 'Engagement', cap: 'Automated messages keep customers informed', items: [{ art: 'mail', title: 'Service reminder', sub: 'Sent automatically' }, { art: 'calendar', title: 'Appointment', sub: 'Confirmed' }, { art: 'chat', title: 'Follow-up', sub: 'After delivery' }] },
        { type: 'pipeline', chapter: 'Tracking', cap: 'Every car is tracked through the workshop', stages: ['Booked', 'In service', 'Ready', 'Delivered'], counts: [7, 5, 2, 11], card: { label: 'Customer car', art: 'car' }, ghosts: ['suv', 'car'] },
        { type: 'hub', chapter: 'Access', cap: 'Each role sees exactly what it needs', center: 'Service', centerArt: 'key', nodes: [{ label: 'Admin', art: 'office' }, { label: 'Service advisor', art: 'mechanic' }, { label: 'Customers', art: 'person3' }, { label: 'Reports', art: 'chart' }] },
        { type: 'dashboard', chapter: 'Analytics', cap: 'Real-time analytics for PM, GR and BP', title: 'Service analytics', nav: ['Dashboard', 'PM', 'GR', 'BP'],
          views: [
            { kind: 'line', kpis: [['412', 'Cars serviced', 'This month'], ['₹38.6L', 'Revenue', 'This month'], ['4.8★', 'CSAT', 'Customers']],
              labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4'], values: [86, 102, 108, 116] },
            { kind: 'bars', kpis: [['218', 'PM jobs', 'This month'], ['1.6 h', 'Avg. time', 'Per car'], ['94%', 'On time', 'Via reminders']],
              labels: ['Oil', 'Filters', 'Brakes', 'Tyres', 'AC'], values: [218, 164, 92, 77, 58] },
            { kind: 'table', kpis: [['124', 'GR jobs', '18 open'], ['2.4 days', 'Turnaround', 'Average'], ['₹14,200', 'Avg. ticket', 'Per job']],
              rows: [['MH 12 AB 4521', 'Brake pads', 'In service', 'Ready'], ['MH 14 CD 8812', 'Clutch', 'Booked', 'In service'], ['MH 12 EF 1190', 'Suspension', 'Delivered']] },
            { kind: 'donut', kpis: [['70', 'BP jobs', 'This month'], ['₹61,500', 'Avg. claim', 'Insurance'], ['5.2 days', 'Turnaround', 'Average']], center: '70 jobs',
              parts: [['Dents', 41], ['Paint', 33], ['Glass', 14], ['Polish', 12]] },
          ] },
      ],
      outcome: { text: 'A more efficient service department and a better experience for every customer.', items: ['Automated reminders', 'Tracked services', 'Real-time analytics'] },
      outro: 'Real-time service analytics',
    },
    'b2b-gift-marketplace': {
      name: 'Greeto', look: 'tint', move: 'push', tagline: 'B2B gifting marketplace', accent: '#e8586b',
      brief: { text: 'Connect gift resellers and manufacturers in one marketplace, with admins overseeing it all.',
        items: [{ label: 'Resellers', art: 'store' }, { label: 'Manufacturers', art: 'factory' }, { label: 'Admins', art: 'office' }, { label: 'Gifts', art: 'gift' }] },
      hero: { kind: 'gift', opts: { color: '#ff5a6e', products: ['basket', 'watch', 'headphone'] }, chapter: 'The marketplace', title: 'Greeto', cap: 'Resellers and manufacturers in one ecosystem', tags: ['Resellers', 'Manufacturers', 'Admins'] },
      scenes: [
        { type: 'apps', chapter: 'Resellers', cap: 'Resellers browse, order and grow in their own app', items: [{ label: 'Browse', job: 'Catalogue', art: 'gift', color: '#e8586b', rows: ['Festive hampers', 'Desk kits', 'Tech gifts'], done: '3 saved' }, { label: 'Order', job: 'Bulk orders', art: 'box', color: '#f5a524', rows: ['250 hampers', 'Logo print', 'Ship to 12 cities'], done: 'Order placed' }, { label: 'Grow', job: 'Sales', art: 'growth', color: '#3d5afe', rows: ['₹4.2L this month', '+18% repeat', '9 new clients'], done: 'Top reseller' }] },
        { type: 'products', chapter: 'Discovery', cap: 'AI finds the right gift for each client', query: 'Festive gifts for clients', ai: true, pick: 1, badge: 'Recommended', items: [{ art: 'gift', label: 'Gift box', sub: 'Festive' }, { art: 'basket', label: 'Hamper', sub: 'Corporate' }, { art: 'books', label: 'Planner', sub: 'Everyday use' }] },
        { type: 'flow', chapter: 'Manufacturers', cap: 'Manufacturers receive orders and scale production', steps: [{ label: 'Order', art: 'clipboard' }, { label: 'Produced', art: 'factory' }, { label: 'Shipped', art: 'truck' }] },
        { type: 'inventory', chapter: 'Dispatch', cap: 'Stock and dispatch are automated end to end', order: 'Gifts dispatched', items: [{ art: 'gift', label: 'Gift boxes' }, { art: 'basket', label: 'Hampers' }, { art: 'books', label: 'Planners' }, { art: 'tag', label: 'Custom' }] },
        { type: 'dashboard', chapter: 'Admin', cap: 'Admins oversee the whole marketplace', title: 'Greeto admin', nav: ['Overview', 'Resellers', 'Makers', 'Orders'],
          views: [
            { kind: 'bars', kpis: [['₹1.9Cr', 'GMV', 'This quarter'], ['1,420', 'Orders', '+24%'], ['312', 'Buyers', 'Companies']],
              labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], values: [18, 22, 21, 27, 31, 38], display: ['₹18L', '₹22L', '₹21L', '₹27L', '₹31L', '₹38L'] },
            { kind: 'table', kpis: [['486', 'Resellers', 'Growing'], ['62', 'New', 'This month'], ['₹3.8L', 'Avg. order', 'Per reseller']],
              rows: [['Giftly Co.', 'Mumbai', 'Active'], ['Pack & Bow', 'Delhi', 'Pending', 'Active'], ['Corporate Joy', 'Pune', 'Active']] },
            { kind: 'donut', kpis: [['128', 'Makers', 'Scaling'], ['4,900', 'SKUs', 'Live'], ['97%', 'Fill rate', 'Orders']], center: '4,900 SKUs',
              parts: [['Hampers', 36], ['Stationery', 24], ['Tech', 22], ['Apparel', 18]] },
            { kind: 'line', kpis: [['1,420', 'Orders', 'This quarter'], ['98%', 'On time', 'Delivered'], ['3.2 days', 'Lead time', 'Average']],
              labels: ['W1', 'W2', 'W3', 'W4', 'W5', 'W6'], values: [180, 205, 221, 238, 262, 314] },
          ] },
      ],
      outcome: { text: 'Resellers grow their business, manufacturers scale production, and admins oversee it effortlessly.', items: ['Scalable', 'Automated', 'Efficient'] },
      outro: 'Gifting, streamlined',
    },
    'global-payment-transfer-platform': {
      name: 'Stablepay', look: 'noir', move: 'slide', tagline: 'The easiest way to transfer your money', accent: '#6b67b8',
      brief: { text: 'Make cross-border transfers fast, low-cost and safe, without traditional banking intermediaries.',
        items: [{ label: 'Global', art: 'earth' }, { label: 'Blockchain', art: 'link' }, { label: 'Stablecoins', art: 'coin' }, { label: 'Secure', art: 'lock' }] },
      hero: { kind: 'globe', opts: { color: '#6b67b8' }, chapter: 'The platform', title: 'Stablepay', cap: 'Fast, low-cost payments across borders', tags: ['USD → INR', 'Stablecoins', 'Cross-border'] },
      scenes: [
        { type: 'cards', chapter: 'The old way', cap: 'Banks add intermediaries; Stablepay goes direct', items: [{ art: 'bank', title: 'Banks', sub: 'Many intermediaries', chip: 'Slow' }, { art: 'bolt', title: 'Stablepay', sub: 'Direct on-chain transfer', chip: 'Fast' }, { art: 'moneybag', title: 'Costs', sub: 'Lower transaction costs', chip: 'Low-cost' }] },
        { type: 'transfer', chapter: 'Send', cap: 'Money leaves one country and lands in another', from: { label: 'USD', sub: 'Your wallet', art: 'purse' }, to: { label: 'INR', sub: 'Receiver', art: 'purse' }, token: 'coin', note: 'Transferred quickly & safely' },
        { type: 'flow', chapter: 'Stablecoins', cap: 'Stablecoins carry the value between currencies', steps: [{ label: 'USD', art: 'banknote' }, { label: 'Stablecoin', art: 'coin' }, { label: 'INR', art: 'rupee' }] },
        { type: 'chain', chapter: 'Blockchain', cap: 'Every step is recorded on the blockchain', blocks: ['Sent', 'Verified', 'Settled', 'Received'] },
        { type: 'hub', chapter: 'Who it serves', cap: 'For individuals and businesses worldwide', center: 'Stablepay', centerArt: 'earth', nodes: [{ label: 'Individuals', art: 'person' }, { label: 'Businesses', art: 'brief' }, { label: 'Families', art: 'person2' }, { label: 'Freelancers', art: 'office' }] },
      ],
      outcome: { text: 'Funds move quickly, safely and affordably, for anyone, anywhere.', items: ['Fast', 'Low-cost', 'Secure'] },
      outro: 'Fast · low-cost · secure',
    },
    'cma-report-generation-software': {
      name: 'CMA Reports', look: 'blueprint', move: 'cut', align: 'left', tagline: 'Credit Monitoring Arrangement reports, automated', accent: '#c0392b',
      brief: { text: 'Automate the preparation of Credit Monitoring Arrangement reports, from data tables to the final PDF.',
        items: [{ label: 'Data', art: 'ledger' }, { label: 'Charts', art: 'chart' }, { label: 'Cloud', art: 'cloud' }, { label: 'Export', art: 'receipt' }] },
      hero: { kind: 'chart', opts: { color: '#c0392b' }, chapter: 'The platform', title: 'CMA Reports', cap: 'Every data table and chart a CMA report needs', tags: ['Data tables', 'Charts', 'ReactJS · NodeJS'] },
      scenes: [
        { type: 'document', chapter: 'Data tables', cap: 'Data tables are built for you', title: 'CMA data', stamp: 'Complete', grid: [['₹ Cr', 'FY23', 'FY24', 'FY25'], ['Sales', '8.9', '10.5', '12.4'], ['EBITDA', '1.6', '1.9', '2.3'], ['PAT', '0.9', '1.2', '1.6'], ['Net worth', '4.2', '5.1', '6.4']] },
        { type: 'dashboard', chapter: 'Charts', cap: 'Charts explain the numbers', title: 'Report charts', nav: ['Tables', 'Charts', 'Summary', 'Export'],
          views: [
            { kind: 'table', kpis: [['₹12.4Cr', 'Turnover', 'FY 2025'], ['₹2.1Cr', 'Working capital', 'Assessed'], ['1.42', 'Current ratio', 'Healthy']],
              rows: [['Balance sheet', 'FY 2023–25', 'Complete'], ['Cash flow', 'Projected', 'Draft', 'Complete'], ['Ratio analysis', '14 ratios', 'Complete']] },
            { kind: 'line', kpis: [['18.6%', 'Growth', 'Year on year'], ['₹3.4Cr', 'Net profit', 'FY 2025'], ['12.8%', 'Net margin', 'FY 2025']],
              labels: ['FY21', 'FY22', 'FY23', 'FY24', 'FY25'], values: [6.1, 7.4, 8.9, 10.5, 12.4], fmt: ['₹', 'Cr', 1] },
            { kind: 'donut', kpis: [['₹5.5Cr', 'Limit sought', 'From bank'], ['1.38', 'DSCR', 'Average'], ['0.9', 'Debt / equity', 'Ratio']], center: '₹5.5Cr',
              parts: [['Term loan', 44], ['Cash credit', 31], ['Own funds', 25]] },
            { kind: 'bars', kpis: [['46', 'Reports', 'This month'], ['2 min', 'Prep time', 'Per report'], ['100%', 'Bank format', 'Compliant']],
              labels: ['PDF', 'Excel', 'Cloud'], values: [28, 14, 4] },
          ] },
        { type: 'flow', chapter: 'Cloud', cap: 'Prepare, edit and finalise in the cloud', steps: [{ label: 'Prepare', art: 'memo' }, { label: 'Edit', art: 'pen' }, { label: 'Finalise', art: 'check' }] },
        { type: 'tiles', chapter: 'Export', cap: 'Download the report as PDF or Excel', items: [{ art: 'pdf', label: 'PDF', sub: 'Ready to submit' }, { art: 'xls', label: 'Excel', sub: 'Every table' }, { art: 'cloud', label: 'Cloud', sub: 'Saved online' }] },
        { type: 'checklist', chapter: 'Efficiency', cap: 'Report preparation, done efficiently', art: 'chart', items: [{ label: 'Data entered', art: 'ledger' }, { label: 'Tables built', art: 'dividers' }, { label: 'Charts generated', art: 'growth' }, { label: 'Report finalised', art: 'receipt' }] },
      ],
      outcome: { text: 'Detailed CMA reports, prepared and finalised efficiently in the cloud.', items: ['Data tables & charts', 'PDF & Excel', 'Cloud-based'] },
      outro: 'ReactJS · NodeJS',
    },
    'recruitment-platform': {
      name: 'Find Your Work', look: 'studio', move: 'wipe', align: 'left', tagline: 'Hiring, from application to offer letter', accent: '#3b5bdb',
      brief: { text: 'Make hiring simple for businesses of all types, from the job post to the offer letter.',
        items: [{ label: 'Listings', art: 'brief' }, { label: 'Chat', art: 'chat' }, { label: 'Tracking', art: 'clipboard' }, { label: 'Analytics', art: 'chart' }] },
      hero: { kind: 'laptop', opts: { screen: { web: true, accent: '#1a3ee8', title: 'Hiring', nav: ['Job postings', 'Candidates', 'Chat', 'Analytics'], tiles: [['Postings', 'Live'], ['Candidates', 'Tracked'], ['Chats', 'Real-time']] } },
        chapter: 'The platform', title: 'Find Your Work', cap: 'Employers find, manage and track candidates', tags: ['Employers', 'Candidates', 'Real-time chat'] },
      scenes: [
        { type: 'cards', chapter: 'Job listings', cap: 'An employer posts new roles in minutes', items: [{ art: 'palette', title: 'Designer', sub: 'Full time', chip: 'Live' }, { art: 'laptop', title: 'Developer', sub: 'Remote', chip: 'Live' }, { art: 'chart', title: 'Analyst', sub: 'On site', chip: 'Draft' }] },
        { type: 'chat', chapter: 'Chat', cap: 'Employers and candidates chat in real time', title: 'Employer', status: 'Online', people: ['office', 'person2'], messages: [['in', 'Hi! Is the role still open?'], ['out', 'It is. Shall we set up a call?'], ['in', 'Great, tomorrow works'], ['out', 'Invite sent']] },
        { type: 'pipeline', chapter: 'Progress', cap: 'Each candidate is tracked through every stage', stages: ['Applied', 'Interview', 'Selected', 'Offer'], counts: [18, 6, 3, 1], card: { label: 'Candidate', art: 'person2' }, ghosts: ['person', 'person3', 'office2'] },
        { type: 'document', chapter: 'Offer', cap: 'The offer letter is signed and sent', title: 'Offer Letter', stamp: 'Signed', sent: 'Sent to candidate', fields: [['Candidate', 'Priya Sharma'], ['Role', 'Product designer'], ['CTC', '₹18,00,000 a year'], ['Location', 'Bengaluru'], ['Joining', '1 November']] },
        { type: 'dashboard', chapter: 'Analytics', cap: 'Analytics show how hiring is going', title: 'Hiring analytics', nav: ['Overview', 'Jobs', 'Candidates', 'Reports'],
          views: [
            { kind: 'bars', kpis: [['1,240', 'Applications', 'This month'], ['248', 'Interviews', 'Scheduled'], ['42', 'Offers', 'Sent']],
              labels: ['Applied', 'Screened', 'Interview', 'Selected', 'Offer'], values: [1240, 610, 248, 86, 42] },
            { kind: 'table', kpis: [['38', 'Open roles', 'Live'], ['9', 'Drafts', 'Unpublished'], ['18 days', 'Time to hire', 'Average']],
              rows: [['Product designer', 'Bengaluru', 'Live'], ['Backend developer', 'Remote', 'Live'], ['Data analyst', 'Pune', 'Draft', 'Live']] },
            { kind: 'donut', kpis: [['1,240', 'Candidates', 'This month'], ['4.6', 'Interview score', 'Average'], ['71%', 'Offers accepted', 'Rate']], center: '1,240 people',
              parts: [['Job boards', 46], ['Direct', 24], ['Referrals', 18], ['Campus', 12]] },
            { kind: 'line', kpis: [['42', 'Hires', 'This month'], ['₹14.5L', 'Avg. CTC', 'Offers'], ['+22%', 'Hires', 'vs. last month']],
              labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], values: [21, 26, 24, 31, 35, 42] },
          ] },
      ],
      outcome: { text: 'Businesses save time finding the best candidates, and candidates find the right employer.', items: ['Faster hiring', 'Clear progress', 'Real-time chat'] },
      outro: 'The right candidate, the right employer',
    },
    'task-staff-and-document-management-platform': {
      name: 'Task & Docs', look: 'dots', move: 'cut', tagline: 'For insurance and investment agencies', accent: '#4f86a8',
      brief: { text: 'Digitally transform insurance and investment agencies: tasks, staff and documents in one app.',
        items: [{ label: 'Tasks', art: 'clipboard' }, { label: 'Staff', art: 'office' }, { label: 'Documents', art: 'folder' }, { label: 'Messaging', art: 'chat' }] },
      hero: { kind: 'folders', opts: { color: '#5b8aa6' }, chapter: 'The app', title: 'Task & Docs', cap: 'Tasks, staff and documents in one place', tags: ['Tasks', 'Staff', 'Documents'] },
      scenes: [
        { type: 'hub', chapter: 'The team', cap: 'Built for admins, heads, field and office staff', center: 'Agency', centerArt: 'brief', nodes: [{ label: 'Admin', art: 'office' }, { label: 'Heads', art: 'office2' }, { label: 'Field staff', art: 'person2' }, { label: 'Office staff', art: 'person' }] },
        { type: 'pipeline', chapter: 'Tasks', cap: 'Tasks are assigned, updated and followed up', stages: ['Assigned', 'Pending', 'Follow-up', 'Done'], counts: [8, 5, 3, 14], card: { label: 'Collect papers', art: 'doc' }, ghosts: ['clipboard', 'doc', 'memo'] },
        { type: 'chat', chapter: 'Messaging', cap: 'Real-time messaging over WebSockets', title: 'Team', status: 'Online', people: ['office2', 'person2'], messages: [['in', 'Client papers collected?'], ['out', 'Yes, uploading now'], ['in', 'Great, marking it done']] },
        { type: 'products', chapter: 'Documents', cap: 'Documents are filed and found by family', query: 'Sharma family documents', pick: 0, badge: 'Found', items: [{ art: 'folder', label: 'Policies', sub: 'Insurance' }, { art: 'growth', label: 'Investments', sub: 'Holdings' }, { art: 'doc', label: 'Documents', sub: 'Uploaded' }] },
        { type: 'devices', chapter: 'Cross-platform', cap: 'Every device in sync, with secure storage', label: 'Secure document storage', art: 'lock' },
        { type: 'checklist', chapter: 'Efficiency', cap: 'Work flows faster from task to file', art: 'check', items: [{ label: 'Task assigned', art: 'clipboard' }, { label: 'Progress tracked', art: 'chart' }, { label: 'Followed up', art: 'bell' }, { label: 'Filed & found', art: 'folder' }] },
      ],
      outcome: { text: 'Teams collaborate in real time, heads track every task, and any file is found in seconds.', items: ['Task follow-ups', 'Family-wise files', 'Secure storage'] },
      outro: 'Agencies, digitally transformed',
    },
    'educational-courses-and-lms-platform': {
      name: 'Learning', look: 'tint', move: 'push', align: 'left', tagline: 'Courses, learners and VR', accent: '#3d8bfd',
      brief: { text: 'One platform for courses, a learning management system and immersive VR lessons.',
        items: [{ label: 'Courses', art: 'books' }, { label: 'LMS', art: 'desktop' }, { label: 'Learners', art: 'student' }, { label: 'VR', art: 'vr' }] },
      hero: { kind: 'vr', opts: { color: '#3d8bfd' }, chapter: 'Immersive', title: 'VR lessons', cap: 'VR content for immersive learning', tags: ['VR content', 'Courses', 'Learners'] },
      scenes: [
        { type: 'products', chapter: 'Discover', cap: 'Search and AI recommendations find the right course', query: 'UI/UX design', ai: true, pick: 0, badge: 'For you', items: [{ art: 'palette', label: 'UI/UX with Figma', sub: 'Recommended' }, { art: 'laptop', label: 'Web design', sub: 'Related' }, { art: 'vr', label: 'VR lesson', sub: 'Immersive' }] },
        { type: 'cards', chapter: 'Courses', cap: 'Courses for every kind of learner', items: [{ art: 'palette', title: 'UI/UX design', sub: 'With Figma', chip: 'New' }, { art: 'laptop', title: 'Development', sub: 'Hands-on' }, { art: 'vr', title: 'VR lessons', sub: 'Immersive' }] },
        // Weekly course progress on the learner dashboard: shape only.
        { type: 'bars', chapter: 'Dashboard', cap: 'Learners follow their progress on a dashboard', art: 'student', artLabel: 'Your week', readout: ['1.5 h', '2.2 h', '1.7 h', '2.5 h', '2 h'], sub: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], display: ['1.5h', '2.2h', '1.7h', '2.5h', '2h'], labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], values: [0.55, 0.8, 0.62, 0.9, 0.72] },
        { type: 'dashboard', chapter: 'LMS', cap: 'The LMS runs courses, students and centres', title: 'LMS', nav: ['Dashboard', 'Courses', 'Students', 'Reports'],
          views: [
            { kind: 'line', kpis: [['8,420', 'Learners', 'Active'], ['36', 'Courses', 'Live'], ['12', 'Centres', 'Network']],
              labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], values: [5200, 5900, 6400, 7100, 7800, 8420] },
            { kind: 'table', kpis: [['36', 'Courses', 'All courses'], ['4.7★', 'Rating', 'Average'], ['82%', 'Completion', 'Rate']],
              rows: [['UI/UX design', 'Batch 12', 'Live'], ['Web design', 'Batch 7', 'Enrolling', 'Live'], ['VR lessons', 'Batch 3', 'Draft', 'Published']] },
            { kind: 'donut', kpis: [['8,420', 'Students', 'Enrolled'], ['1,120', 'New', 'This month'], ['64%', 'On mobile', 'Learners']], center: '8,420 learners',
              parts: [['UI/UX', 38], ['Web', 29], ['VR', 19], ['Other', 14]] },
            { kind: 'bars', kpis: [['2,310', 'Certificates', 'Awarded'], ['6.2 h', 'Weekly time', 'Per learner'], ['91%', 'Satisfaction', 'Survey']],
              labels: ['Pune', 'Delhi', 'Mumbai', 'Online'], values: [420, 380, 510, 1000] },
          ] },
        { type: 'document', chapter: 'Certificate', cap: 'Finishing a course earns a certificate', title: 'Certificate', stamp: 'Awarded', fields: [['Awarded to', 'Rohan Mehta'], ['Course', 'UI/UX design'], ['Batch', '12 · Pune'], ['Grade', 'A · 92%'], ['Issued', '26 Sep 2026']] },
      ],
      outcome: { text: 'Learning that works on screen or in VR, with every learner’s progress in view.', items: ['Website & LMS', 'AI recommendations', 'VR content'] },
      outro: 'Learn on screen or in VR',
    },
    'storyboard-creation-for-films-with-ai': {
      name: 'Storyboard AI', look: 'noir', move: 'cut', tagline: 'Scripts into storyboards, in minutes', accent: '#e8672c',
      brief: { text: 'Turn scripts into visual storyboards in minutes, for filmmakers, advertisers and creators.',
        items: [{ label: 'Script', art: 'memo' }, { label: 'Scenes', art: 'clap' }, { label: 'Frames', art: 'film' }, { label: 'Editing', art: 'pen' }] },
      hero: { kind: 'clapper', opts: { color: '#ff5b1f', label: 'STORYBOARD' }, chapter: 'The tool', title: 'Storyboard AI', cap: 'Generative AI turns a script into a storyboard', tags: ['Script', 'Scenes', 'Frames'] },
      scenes: [
        { type: 'frames', chapter: 'Script to frames', cap: 'AI breaks the script down, scene by scene', title: 'SCENE 1', script: ['EXT. HOUSE - DAY', 'Anni runs outside.', 'The sun is out.', 'She waves at a friend.'],
          frames: [{ art: 'house', art2: 'sun' }, { art: 'person2', art2: 'house' }, { art: 'sun', art2: 'tree', sky: '#ffd08a' }, { art: 'person2', art2: 'person' }, { art: 'tree', art2: 'person2' }, { art: 'house', art2: 'tree', sky: '#b7a6ff' }] },
        { type: 'checklist', chapter: 'Consistency', cap: 'Characters and style stay consistent', art: 'film', items: [{ label: 'Same characters', art: 'person2' }, { label: 'Visual style', art: 'palette' }, { label: 'Scene by scene', art: 'clap' }, { label: 'Coherent story', art: 'book' }] },
        { type: 'flow', chapter: 'Iteration', cap: 'Any frame can be regenerated until it is right', steps: [{ label: 'Frame', art: 'film' }, { label: 'Regenerate', art: 'ai' }, { label: 'Refined', art: 'sparkle' }] },
        { type: 'tiles', chapter: 'Editing', cap: 'Intuitive tools keep creative control', items: [{ art: 'ai', label: 'Regenerate', sub: 'Any frame' }, { art: 'photo', label: 'Reference', sub: 'Guide the look' }, { art: 'pen', label: 'Edit', sub: 'Fine-tune details' }] },
        { type: 'hub', chapter: 'Who it serves', cap: 'Built for filmmakers, advertisers and creators', center: 'Storyboard', centerArt: 'clap', nodes: [{ label: 'Filmmakers', art: 'video' }, { label: 'Advertisers', art: 'megaphone' }, { label: 'Creators', art: 'person2' }] },
      ],
      outcome: { text: 'Storyboards in minutes, with narrative coherence and full creative control.', items: ['Script to storyboard', 'Consistent scenes', 'Easy iteration'] },
      outro: 'From script to screen',
    },
    'insurance-management-platform': {
      name: 'InsureTech', look: 'paper', move: 'slide', tagline: 'Every policy in one hub', accent: '#e0662f',
      brief: { text: 'Keep every insurance policy in one app, so no premium or coverage update is ever missed.',
        items: [{ label: 'Health', art: 'health' }, { label: 'Auto', art: 'car' }, { label: 'Home', art: 'house' }, { label: 'Life', art: 'umbrella' }] },
      hero: { kind: 'shield', opts: { color: '#e8612c' }, chapter: 'The app', title: 'InsureTech', cap: 'A single hub for every insurance policy', tags: ['Health', 'Auto', 'Life'] },
      scenes: [
        { type: 'cards', chapter: 'All policies', cap: 'Health, auto, life: all stored together', items: [{ art: 'health', title: 'Health', sub: 'Policy stored', color: '#e5484d' }, { art: 'car', title: 'Auto', sub: 'Policy stored', color: '#e8612c' }, { art: 'umbrella', title: 'Life', sub: 'Policy stored', color: '#f5b50a' }] },
        { type: 'notify', chapter: 'Updates', cap: 'Timely notifications for premiums and coverage', items: [{ art: 'bell', title: 'Premium due soon', sub: 'Health policy' }, { art: 'shield', title: 'Coverage updated', sub: 'Auto policy' }, { art: 'check', title: 'Policy renewed', sub: 'Life policy' }] },
        { type: 'calendar', chapter: 'Reminders', cap: 'Payment reminders arrive automatically', month: 'Premiums', day: 12, event: 'Premium due', sub: 'Reminder set', art: 'bell' },
        { type: 'devices', chapter: 'Cross-platform', cap: 'One Flutter app with a modern UI on every device', label: 'Health to auto and more', art: 'shield' },
      ],
      outcome: { text: 'Users manage every type of insurance in one place and never miss a payment.', items: ['Centralised hub', 'Timely notifications', 'Payment reminders'] },
      outro: 'Never miss a premium',
    },
    'social-media-and-social-commerce-platform': {
      name: 'Social', look: 'tint', move: 'wipe', tagline: 'Connect through shared interests', accent: '#6a4cf0',
      brief: { text: 'A social network where shared interests become communities, and communities become a marketplace.',
        items: [{ label: 'Communities', art: 'hands' }, { label: 'Content', art: 'camera' }, { label: 'Marketplace', art: 'bagshop' }, { label: 'Wallet', art: 'coin' }] },
      hero: { kind: 'phone', opts: { accent: '#2a2340', screen: { dark: true, accent: '#5b3cf5', title: 'Discover', items: [['Adrenaline Junkies', 'Community'], ['Market', 'Peer-to-peer'], ['Leaderboard', 'Top creators'], ['Wallet', 'Crypto']] } },
        chapter: 'The app', title: 'Social', cap: 'Social media meets social commerce', tags: ['Singing', 'Dancing', 'Sports'] },
      scenes: [
        { type: 'hub', chapter: 'Communities', cap: 'Members join groups around what they love', center: 'Community', centerArt: 'heart', nodes: [{ label: 'Singing', art: 'mic' }, { label: 'Dancing', art: 'dance' }, { label: 'Sports', art: 'ball' }, { label: 'Adventure', art: 'fire' }] },
        { type: 'live', chapter: 'Share', cap: 'They share content and engage with each other', art: 'photo', label: 'New post', cta: 'Like', host: 'person', feed: ['Loved this!', 'Join our group?', 'See you Saturday'] },
        { type: 'chat', chapter: 'Messaging', cap: 'In-app messaging keeps conversations going', title: 'Adrenaline Junkies', status: 'Group chat', people: ['person', 'person2'], messages: [['in', 'Loved your post!'], ['out', 'Thanks! Join the group?'], ['in', 'Just did']] },
        { type: 'products', chapter: 'Marketplace', cap: 'Members buy and sell peer to peer', pick: 0, badge: 'Make offer', items: [{ art: 'headphone', label: 'Headphones', sub: '@agaoh21' }, { art: 'camera', label: 'Camera', sub: 'Listing' }, { art: 'watch', label: 'Watch', sub: 'Listing' }] },
        { type: 'transfer', chapter: 'Wallet', cap: 'Payments settle through in-app crypto wallets', from: { label: 'Buyer', sub: 'Crypto wallet', art: 'purse' }, to: { label: 'Seller', sub: 'Wallet', art: 'purse' }, token: 'coin' },
        { type: 'podium', chapter: 'Leaderboards', cap: 'Leaderboards reward the most engaging creators', people: ['person2', 'person', 'person3'], labels: ['Top creator', '2nd', '3rd'] },
        { type: 'cards', chapter: 'Brands', cap: 'Brands promote, and every profile is personal', items: [{ art: 'megaphone', title: 'Brands', sub: 'Promotions' }, { art: 'person2', title: 'Profile', sub: 'Personalised', chip: 'You' }, { art: 'star', title: 'Rewards', sub: 'Earn as you engage' }] },
      ],
      outcome: { text: 'A dynamic space where creators, consumers and brands meet, share and trade.', items: ['Communities', 'Peer-to-peer market', 'Crypto wallets'] },
      outro: 'Creators, consumers & brands',
    },
  },

  closing: "Let's connect and build smarter, faster, and stronger - together.",
};
